"""
Facebook Page Auto-Poster with AI-generated captions + images.
- Captions: generated by Claude (Anthropic API)
- Images:   free from Picsum Photos
- Posts:    published via Facebook Graph API
"""
import os, sys, json, time, requests
from datetime import datetime, timezone

FB_PAGE_ID      = os.environ.get("FB_PAGE_ID", "")
FB_PAGE_TOKEN   = os.environ.get("FB_PAGE_TOKEN", "")
ANTHROPIC_KEY   = os.environ.get("ANTHROPIC_API_KEY", "")
POST_SLOT       = os.environ.get("POST_SLOT", "1")
NICHE           = os.environ.get("INSTAGRAM_NICHE", "motivational lifestyle")

BASE_FB  = f"https://graph.facebook.com/v19.0/{FB_PAGE_ID}"
LOG_FILE = "post_log.json"

SLOT_THEMES = {
    "1": "morning motivation and fresh start to the day",
    "2": "productivity tips and mid-morning energy",
    "3": "positive mindset and noon inspiration",
    "4": "lunch break wellness and self-care",
    "5": "afternoon hustle and goal setting",
    "6": "early evening reflection and gratitude",
    "7": "golden hour beauty and lifestyle",
    "8": "night wind-down, rest and tomorrow's mindset",
}

SLOT_PHOTO_IDS = {
    "1": [10, 15, 96, 110, 137, 167, 190, 200],
    "2": [20, 42, 56, 103, 153, 175, 211, 240],
    "3": [37, 64, 82, 116, 144, 180, 219, 250],
    "4": [30, 48, 75, 122, 158, 185, 225, 260],
    "5": [25, 55, 88, 130, 163, 192, 230, 270],
    "6": [45, 68, 92, 135, 170, 198, 235, 280],
    "7": [52, 73, 98, 140, 176, 204, 242, 290],
    "8": [60, 80, 105, 148, 182, 210, 248, 300],
}

def log(msg):
    print(f"[{datetime.now(timezone.utc).strftime('%H:%M:%S')}] {msg}")

def generate_caption(slot):
    theme = SLOT_THEMES.get(slot, "daily inspiration")
    log(f"Generating caption for slot {slot}: {theme}")

    prompt = (
        f"You are a Facebook page content creator in the '{NICHE}' niche.\n"
        f"Write ONE engaging Facebook post for the theme: '{theme}'.\n"
        f"Requirements:\n"
        f"- 2-4 sentences\n"
        f"- Include 2-3 relevant emojis naturally placed\n"
        f"- End with 3-5 hashtags on a new line\n"
        f"- Conversational, authentic tone\n"
        f"- Do NOT include any intro like 'Here is a post:'\n"
        f"Return ONLY the post text."
    )

    r = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-opus-4-5",
            "max_tokens": 300,
            "messages": [{"role": "user", "content": prompt}],
        },
        timeout=30,
    )
    if r.status_code != 200:
        log(f"Anthropic error: {r.status_code} - {r.text}")
        r.raise_for_status()

    caption = r.json()["content"][0]["text"].strip()
    log(f"Caption: {caption[:80]}...")
    return caption

def get_image_url(slot):
    log("Selecting image from Picsum...")
    photo_ids = SLOT_PHOTO_IDS.get(slot, list(range(10, 300, 30)))
    day_of_year = int(datetime.now(timezone.utc).strftime("%j"))
    photo_id = photo_ids[day_of_year % len(photo_ids)]
    image_url = f"https://picsum.photos/id/{photo_id}/1200/630"
    log(f"Resolving image (Picsum ID: {photo_id})...")
    r = requests.get(image_url, timeout=20, allow_redirects=True)
    if r.status_code != 200:
        raise RuntimeError(f"Image not reachable: {r.status_code}")
    final_url = r.url
    log(f"Image URL ready: {final_url[:80]}...")
    return final_url

def post_to_facebook(caption, image_url):
    log("Posting to Facebook Page...")
    # Post photo with caption to Facebook Page
    r = requests.post(
        f"{BASE_FB}/photos",
        data={
            "url": image_url,
            "message": caption,
            "access_token": FB_PAGE_TOKEN,
        },
        timeout=30,
    )
    if r.status_code != 200:
        log(f"FB post error: {r.status_code} - {r.text}")
        r.raise_for_status()
    data = r.json()
    if "id" not in data:
        raise RuntimeError(f"Post failed: {data}")
    log(f"Posted! Post ID: {data['id']}")
    return data["id"]

def save_log(slot, status, post_id="", caption="", error=""):
    entries = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE) as f:
            try: entries = json.load(f)
            except: pass
    entries.append({
        "slot": slot,
        "time": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "post_id": post_id,
        "caption_preview": caption[:100],
        "error": error,
    })
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def main():
    print(f"\n{'='*60}")
    print(f"  Facebook AI AutoPoster  |  Slot {POST_SLOT}  |  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC")
    print(f"  Niche: {NICHE}")
    print(f"{'='*60}\n")

    missing = [k for k, v in {
        "FB_PAGE_ID": FB_PAGE_ID,
        "FB_PAGE_TOKEN": FB_PAGE_TOKEN,
        "ANTHROPIC_API_KEY": ANTHROPIC_KEY,
    }.items() if not v]
    if missing:
        log(f"ERROR: Missing secrets: {', '.join(missing)}")
        sys.exit(1)

    log(f"API Key: sk-ant-...{ANTHROPIC_KEY[-6:]}")
    log(f"FB Page ID: {FB_PAGE_ID}")

    try:
        caption   = generate_caption(POST_SLOT)
        image_url = get_image_url(POST_SLOT)
        post_id   = post_to_facebook(caption, image_url)
        save_log(POST_SLOT, "success", post_id, caption)
        print(f"\n✅  Slot {POST_SLOT} posted to Facebook successfully!\n")
    except Exception as e:
        log(f"FAILED: {e}")
        save_log(POST_SLOT, "error", error=str(e))
        sys.exit(1)

if __name__ == "__main__":
    main()
